### ISSUE TITLE
dns.resolver.resolver does not refer to /etc/hosts before querying resolver

### ISSUE THREAD

**Issue by yzguy** [octodns/octodns-bind#27]
Related #24 #25

`dns.resolver.resolve()` does not refer to `/etc/hosts` before making a query to a resolver it goes straight to a resolver. This generally is fine if you're referring to a remote server, but if it's running on localhost or something that you've set in /etc/hosts it won't work.

We should probably use `socket.getaddrinfo` instead which will look at /etc/hosts and then do a query via resolver if it finds nothing.

**Comment by ross** [comment]
> We should probably we `socket.gethostbyname` instead which will look at /etc/hosts and then do a query via resolver if it finds nothing.

Ah, true. would be a bit tough for people to figure out why their etc/hosts info wasn't getting used.

**Comment by yzguy** [comment]
I actually had it using `socket.gethostbyname` originally, and then I had a toggle for it to use IPv4/IPv6 so that shouldn't be hard to refactor. Right now I believe it's just going to query the name and go for an A record if it exists, if not then i believe it'll go for an AAAA.

I'll fix it and give the option to toggle IPv6 or not with like `ipv6: true`

**Comment by yzguy** [comment]
This is contained in #28
