### ISSUE TITLE
Support AXFR/RF2136 to Azure Private DNS

### ISSUE THREAD

**Issue by benjamin-rousseau-shift** [octodns/octodns-bind#35]
I am trying to keep in sync a zone from my Microsoft DNS Server to an Azure Private DNS.
However it does not seem possible as the Microsoft DNS Server uses an NS entry and Azure Private DNS do not support NS entry.

Would it be possible for this scenario to ignore the NS entries somehow ? 
If I remove the NS entry I get : 
```octodns_bind.AxfrSourceZoneTransferFailed: Unable to Perform Zone Transfer: The DNS zone has no NS RRset at its origin.```

If I have the NS entry I get:
```octodns.provider.SupportsException: azure: root NS record not supported for domain.com.```

**Comment by ross** [comment]
What version of the `AzureProvider` are you using, it looks like it should support ROOT_NS values https://github.com/octodns/octodns-azure/blob/70b8c9153db8ee25e701a5b488f828560f536156/octodns_azure/__init__.py#L903, though there may be some complications around Azure's requiring its own NS values to be included.

Beyond that based on a quick look at the error message it appears to be something that the underlying library throws and not octoDNS, https://github.com/octodns/octodns-bind/blob/a6fb996c4bdd5661374a8ab0cc8bc21fe54dff6f/tests/test_provider_octodns_bind.py#L131, https://github.com/octodns/octodns-bind/blob/a6fb996c4bdd5661374a8ab0cc8bc21fe54dff6f/tests/zones/invalid.zone.tst.

Based on :eye:ing the underlying library's code, https://dnspython.readthedocs.io/en/latest/_modules/dns/zone.html?highlight=from_file# and https://dnspython.readthedocs.io/en/latest/_modules/dns/zone.html?highlight=from_xfr# both state they throw that error and don't appear to have a way to suppress it.

Side note: I'd recommend pasting the stack traces in addition to the specific exception messages as it can be helpful when digging into where errors are coming from.

**Comment by benjamin-rousseau-shift** [comment]
I'm talking specifically about Azure Private DNS Zone which is provider AzurePrivateProvider. ( Latest version ).

It does not support NS, but I'm wondering if there might be a workaround for usecases where we want to sync a axfr/rfc zone to an Azure private DNS zone. 

I'm out of office now but I can give more details tomorrow if needed. 👍

**Comment by ross** [comment]
> It does not support NS, but I'm wondering if there might be a workaround for usecases where we want to sync a axfr/rfc zone to an Azure private DNS zone.

You can disable `strict_supports` to turn that supports exception into a warning, https://github.com/octodns/octodns#strict_supports-work-in-progress. You need to make sure that's the only warning that's printed out afterwards or that you're OK with any others.

**Comment by benjamin-rousseau-shift** [comment]
You are correct it's working fine with strict_supports disabled !
Thank you so much.

I would then suggest that the error thrown, tell you about this with a link to the right section in the README.
