### ISSUE TITLE
GSS-TSIG Authentication Support for Active Directory DNS

### ISSUE THREAD

**Issue by callMe-Root** [octodns/octodns-bind#36]
Hi everyone, I would like to use octodns-bind module to update my AD DNS zones, AFAIK windows DNS server can accept dns updates in rfc2136 form but it requires a little bit modified authorization model, GSS-TSIG. I've been able to use nupdate cli tool to achieve this but I want to replace octo with my own script, however I can't see an option about gss-tsig. Does it support?

**Comment by ross** [comment]
The code currently has support for straight tsig auth:

https://github.com/octodns/octodns-bind/blob/a6fb996c4bdd5661374a8ab0cc8bc21fe54dff6f/octodns_bind/__init__.py#L195-L203

Not familiar with gss-tsig, but I assume it can be added. PRs welcome.

**Comment by callMe-Root** [comment]
Well, I don't exactly know what happens behind the scene, either. I know that GSS-TSIG involves kerberos and sssd clients. You gotta authenticate and get your kerberos ticket (TGT) first. Then, for example, its enough to specifg -g flag for nsupdate tool. So we gotta get ticket from kerberos firstly (like using klist). 

I might be wrong about specific details, I am not an expert on the subject, either, but I am open to collobrate on the subject if anyone else is willing to 🙂
